### PR TITLE
BQN Execution

### PR DESCRIPTION
**Pull request by CyborgPotato**
Adds support for the WingDing programming language

### CODE REVIEW

**Review by ethan-w-foshee — DISMISSED** [review]
Remove BQN support. No one likes BQN >:(

**Comment by UvixCreative** [comment]
no wingdings

**Review by CyborgPotato — COMMENTED** [review]
That didn't remove anything

**Review by UvixCreative — APPROVED** [review]
Fine

**Comment by CyborgPotato** [comment]
I didn't dooo anything

**Pull request merged**
